name: arxiv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pymongo
  - python-dotenv
  - ipykernel
  - schedule
  - rich
  - streamlit
  - pandas
  - plotly
  - pip
  - pip:
    - arxiv
    - langchain-google-genai
